version: '3.8'

services:
  web:
    build: .
    command: bash -c "bin/rails server -b 0.0.0.0"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata:
